In [1]:
# Import the dependencies.
import pandas as pd
import gmaps
import gmaps.datasets
import requests
# Import the API key.
from config import g_key

In [2]:
# Store the CSV you saved created in part one into a DataFrame.
city_data_df = pd.read_csv("weather_data/cities.csv")
city_data_df.head()

,City_ID,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date
0,0,Khatanga,71.9667,102.5000,-30.73,80,0,7.05,RU,2021-01-27 23:32:40
1,1,Colomi,-17.3500,-65.8667,69.80,52,75,17.27,BO,2021-01-27 23:32:40
2,2,Upernavik,72.7868,-56.1549,-3.51,91,99,4.74,GL,2021-01-27 23:32:40
3,3,Butaritari,3.0707,172.7902,80.20,81,82,13.24,KI,2021-01-27 23:27:40
4,4,Waingapu,-9.6567,120.2641,81.07,77,100,12.33,ID,2021-01-27 23:32:40

In [3]:
# Configure gmaps to use your Google API key.
gmaps.configure(api_key=g_key)

In [4]:
# Get the maximum temperature.
max_temp = city_data_df["Max Temp"]
temps = []
for temp in max_temp:
    temps.append(max(temp, 0))

In [8]:
# Heatmap of temperature
# Get the latitude and longitude.
locations = city_data_df[["Lat", "Lng"]]
# Get the maximum temperature.
max_temp = city_data_df["Max Temp"]
# Assign the figure variable.
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)# Assign the heatmap variable.
heat_layer = gmaps.heatmap_layer(locations, weights=temps, dissipating=False, max_intensity=300, point_radius=4)
# Add the heatmap layer.
fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [9]:
# Heatmap of percent humidity
locations = city_data_df[["Lat", "Lng"]]
humidity = city_data_df["Humidity"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=humidity, dissipating=False, max_intensity=300, point_radius=4)

fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [10]:
# Heatmap of percent humidity
locations = city_data_df[["Lat", "Lng"]]
clouds = city_data_df["Cloudiness"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=clouds, dissipating=False, max_intensity=300, point_radius=4)

fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [11]:
# Heatmap of percent humidity
locations = city_data_df[["Lat", "Lng"]]
wind = city_data_df["Wind Speed"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=wind, dissipating=False, max_intensity=300, point_radius=4)

fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [12]:
# Ask the customer to add a minimum and maximum temperature value.
min_temp = float(input("What is the minimum temperature you would like for your trip? "))
max_temp = float(input("What is the maximum temperature you would like for your trip? "))

What is the minimum temperature you would like for your trip? 75
What is the maximum temperature you would like for your trip? 90

In [13]:
# Filter the dataset to find the cities that fit the criteria.
preferred_cities_df = city_data_df.loc[(city_data_df["Max Temp"] <= max_temp) & \
                                       (city_data_df["Max Temp"] >= min_temp)]
preferred_cities_df.head(10)

,City_ID,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date
3,3,Butaritari,3.0707,172.7902,80.20,81,82,13.24,KI,2021-01-27 23:27:40
4,4,Waingapu,-9.6567,120.2641,81.07,77,100,12.33,ID,2021-01-27 23:32:40
6,6,Magdalena,14.1999,121.4290,79.00,94,75,2.30,PH,2021-01-27 23:32:40
11,11,Kavieng,-2.5744,150.7967,84.99,71,89,10.09,PG,2021-01-27 23:32:41
16,16,Puerto Ayora,-0.7393,-90.3518,84.20,70,20,21.85,EC,2021-01-27 23:28:00
18,18,Kloulklubed,7.0419,134.2556,78.80,89,90,4.61,PW,2021-01-27 23:32:42
19,19,Rikitea,-23.1203,-134.9692,79.95,73,92,11.68,PF,2021-01-27 23:32:42
25,25,Georgetown,5.4112,100.3354,79.00,88,20,4.59,MY,2021-01-27 23:28:43
32,32,Hilo,19.7297,-155.0900,77.00,69,90,6.91,US,2021-01-27 23:30:53
33,33,Xochistlahuaca,16.7833,-98.2500,81.93,45,56,4.61,MX,2021-01-27 23:32:44

In [14]:
preferred_cities_df.count()

City_ID       141
City          141
Lat           141
Lng           141
Max Temp      141
Humidity      141
Cloudiness    141
Wind Speed    141
Country       141
Date          141
dtype: int64

In [15]:
# Create DataFrame called hotel_df to store hotel names along with city, country, max temp, and coordinates.
hotel_df = preferred_cities_df[["City", "Country", "Max Temp", "Lat", "Lng"]].copy()
hotel_df["Hotel Name"] = ""
hotel_df.head(10)

              City Country  Max Temp      Lat       Lng Hotel Name
3       Butaritari      KI     80.20   3.0707  172.7902
4         Waingapu      ID     81.07  -9.6567  120.2641
6        Magdalena      PH     79.00  14.1999  121.4290
11         Kavieng      PG     84.99  -2.5744  150.7967
16    Puerto Ayora      EC     84.20  -0.7393  -90.3518
18     Kloulklubed      PW     78.80   7.0419  134.2556
19         Rikitea      PF     79.95 -23.1203 -134.9692
25      Georgetown      MY     79.00   5.4112  100.3354
32            Hilo      US     77.00  19.7297 -155.0900
33  Xochistlahuaca      MX     81.93  16.7833  -98.2500

In [16]:
# Set parameters to search for a hotel.
params = {
    "radius": 5000,
    "type": "lodging",
    "key": g_key
}

In [20]:
# Iterate through the DataFrame.
for index, row in hotel_df.iterrows():
    # Get the latitude and longitude.
    lat = row["Lat"]
    lng = row["Lng"]

    # Add the latitude and longitude to location key for the params dictionary.
    params["location"] = f"{lat},{lng}"

    # Use the search term: "lodging" and our latitude and longitude.
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"
    # Make request and get the JSON data from the search.
    hotels = requests.get(base_url, params=params).json()
    # Grab the first hotel from the results and store the name.
    # Grab the first hotel from the results and store the name.
try:
    hotel_df.loc[index, "Hotel Name"] = hotels["results"][0]["name"]
except (IndexError):
    print("Hotel not found... skipping.")

In [21]:
hotel_df.head(10)

,City,Country,Max Temp,Lat,Lng,Hotel Name
3,Butaritari,KI,80.20,3.0707,172.7902,Isles Sunset Lodge
4,Waingapu,ID,81.07,-9.6567,120.2641,Pondok Wisata Elim
6,Magdalena,PH,79.00,14.1999,121.4290,Samparada & Gestiada Residences
11,Kavieng,PG,84.99,-2.5744,150.7967,Nusa Island Retreat
16,Puerto Ayora,EC,84.20,-0.7393,-90.3518,Castillo Galapagos
18,Kloulklubed,PW,78.80,7.0419,134.2556,Storyboard Beach Resort
19,Rikitea,PF,79.95,-23.1203,-134.9692,Pension Maro'i
25,Georgetown,MY,79.00,5.4112,100.3354,Cititel Penang
32,Hilo,US,77.00,19.7297,-155.0900,Hilo Hawaiian Hotel
33,Xochistlahuaca,MX,81.93,16.7833,-98.2500,La frontera

In [23]:
# Add a heatmap of temperature for the vacation spots and marker for each city.
locations = hotel_df[["Lat", "Lng"]]
max_temp = hotel_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=max_temp,
             dissipating=False, max_intensity=300, point_radius=4)
marker_layer = gmaps.marker_layer(locations)
fig.add_layer(heat_layer)
fig.add_layer(marker_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [24]:
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Max Temp</dt><dd>{Max Temp} °F</dd>
</dl>
"""
# Store the DataFrame Row.
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]

In [25]:
# Add a heatmap of temperature for the vacation spots and a pop-up marker for each city.
locations = hotel_df[["Lat", "Lng"]]
max_temp = hotel_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=max_temp,dissipating=False,
             max_intensity=300, point_radius=4)
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(heat_layer)
fig.add_layer(marker_layer)

# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))